/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import entidades.Cliente;
import javax.swing.JOptionPane;
import model.dao.ClienteDAO;

/**
 *
 * @author Layza
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form LoginTela
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome4 = new javax.swing.JLabel();
        painelGradiente = new keeptoo.KGradientPanel();
        painelLogin = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblCadastrar = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        pwdSenha = new javax.swing.JPasswordField();
        txtCPF = new javax.swing.JFormattedTextField();
        txtIdade = new javax.swing.JFormattedTextField();
        lblPossuiConta = new javax.swing.JLabel();
        lblEntre = new javax.swing.JLabel();
        btnCadastro = new com.k33ptoo.components.KButton();
        jLabel2 = new javax.swing.JLabel();

        nome4.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        nome4.setText("Nome");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de cadastro");
        setUndecorated(true);
        setResizable(false);

        painelGradiente.setkEndColor(new java.awt.Color(255, 71, 0));
        painelGradiente.setkGradientFocus(400);
        painelGradiente.setkStartColor(new java.awt.Color(255, 189, 91));
        painelGradiente.setPreferredSize(new java.awt.Dimension(926, 578));

        painelLogin.setBackground(new java.awt.Color(255, 255, 255));

        lblNome.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 34, 5));
        lblNome.setText("Nome");

        lblSenha.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(255, 34, 5));
        lblSenha.setText("Senha");

        lblIdade.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        lblIdade.setForeground(new java.awt.Color(255, 34, 5));
        lblIdade.setText("Idade");

        lblCPF.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        lblCPF.setForeground(new java.awt.Color(255, 34, 5));
        lblCPF.setText("CPF");

        lblCadastrar.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblCadastrar.setForeground(new java.awt.Color(255, 34, 5));
        lblCadastrar.setText("Cadastrar");

        txtNome.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        txtNome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 33, 5)));
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        pwdSenha.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        pwdSenha.setToolTipText("");
        pwdSenha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 33, 5)));
        pwdSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdSenhaActionPerformed(evt);
            }
        });

        txtCPF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 33, 5)));
        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPF.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N

        txtIdade.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 33, 5)));
        txtIdade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##"))));
        txtIdade.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        txtIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdadeActionPerformed(evt);
            }
        });

        lblPossuiConta.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblPossuiConta.setForeground(new java.awt.Color(102, 102, 102));
        lblPossuiConta.setText("Já possui uma conta?");

        lblEntre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEntre.setForeground(new java.awt.Color(255, 35, 5));
        lblEntre.setText("Entre");
        lblEntre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEntreMouseClicked(evt);
            }
        });

        btnCadastro.setText("Cadastrar");
        btnCadastro.setToolTipText("");
        btnCadastro.setActionCommand("Fazer login");
        btnCadastro.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        btnCadastro.setkBackGroundColor(new java.awt.Color(0, 0, 255));
        btnCadastro.setkEndColor(new java.awt.Color(153, 153, 153));
        btnCadastro.setkFillButton(false);
        btnCadastro.setkForeGround(new java.awt.Color(255, 35, 5));
        btnCadastro.setkHoverColor(new java.awt.Color(0, 0, 255));
        btnCadastro.setkHoverEndColor(new java.awt.Color(255, 35, 5));
        btnCadastro.setkHoverForeGround(new java.awt.Color(255, 35, 5));
        btnCadastro.setkHoverStartColor(new java.awt.Color(255, 35, 5));
        btnCadastro.setkIndicatorColor(new java.awt.Color(0, 0, 255));
        btnCadastro.setkPressedColor(new java.awt.Color(153, 153, 153));
        btnCadastro.setkSelectedColor(new java.awt.Color(0, 0, 255));
        btnCadastro.setkStartColor(new java.awt.Color(153, 153, 153));
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelLoginLayout = new javax.swing.GroupLayout(painelLogin);
        painelLogin.setLayout(painelLoginLayout);
        painelLoginLayout.setHorizontalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCadastrar)
                .addGap(115, 115, 115))
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLoginLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblIdade)
                            .addComponent(txtNome)
                            .addComponent(lblSenha)
                            .addComponent(lblNome)
                            .addComponent(lblCPF)
                            .addComponent(pwdSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(txtCPF)
                            .addComponent(txtIdade)))
                    .addGroup(painelLoginLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lblPossuiConta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEntre))
                    .addGroup(painelLoginLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btnCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        painelLoginLayout.setVerticalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblCadastrar)
                .addGap(35, 35, 35)
                .addComponent(lblNome)
                .addGap(0, 0, 0)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSenha)
                .addGap(0, 0, 0)
                .addComponent(pwdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCPF)
                .addGap(0, 0, 0)
                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblIdade)
                .addGap(0, 0, 0)
                .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPossuiConta)
                    .addComponent(lblEntre))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelGradienteLayout = new javax.swing.GroupLayout(painelGradiente);
        painelGradiente.setLayout(painelGradienteLayout);
        painelGradienteLayout.setHorizontalGroup(
            painelGradienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelGradienteLayout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addComponent(painelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(308, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelGradienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(17, 17, 17))
        );
        painelGradienteLayout.setVerticalGroup(
            painelGradienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGradienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(16, 16, 16)
                .addComponent(painelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        getContentPane().add(painelGradiente, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void pwdSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdSenhaActionPerformed

    private void txtIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdadeActionPerformed

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        // TODO add your handling code here:
        if(txtNome.getText().strip().isEmpty() || new String(pwdSenha.getPassword()).strip().isEmpty() || txtCPF.getText().strip().isEmpty() || txtIdade.getText().strip().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informações incompletas. "); 
        } 
        else if(Integer.parseInt(txtIdade.getText()) < 18){
            JOptionPane.showMessageDialog(null, "Idade mínima de 18 anos."); 
        }
        else{
            Cliente c = new Cliente();
            ClienteDAO dao = new ClienteDAO();

            c.setNome(txtNome.getText().strip());
            c.setSenha(new String(pwdSenha.getPassword()).strip());
            c.setCPF(txtCPF.getText());
            c.setIdade(Integer.parseInt(txtIdade.getText()));

            dao.create(c);
            new LoginTela().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void lblEntreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEntreMouseClicked
        // TODO add your handling code here:
        LoginTela login = new LoginTela();
        login.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lblEntreMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnCadastro;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCadastrar;
    private javax.swing.JLabel lblEntre;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPossuiConta;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel nome4;
    private keeptoo.KGradientPanel painelGradiente;
    private javax.swing.JPanel painelLogin;
    private javax.swing.JPasswordField pwdSenha;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JFormattedTextField txtIdade;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
